name: DLS History

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run DLS Script
        run: |
          python dls_history.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add *.csv || true

          git commit -m "Update DLS history" || echo "No changes"

          git push
